### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by brendy1250** [mylxsw/aidea#11]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

_Originally posted by @mylxsw in https://github.com/mylxsw/aidea/discussions/5_

**Comment by prasun276** [comment]
Hi I'm Prasun, a programmer/developer and I am new to this open source and contribution world. I love to design and develop apps which can be used to solve real world problems. I am interested in Android, Web, AI, LLMs and Artificial Intelligence. I like to learn new tools and technologies which could be used to solve some complex problems. I would love to be a part of this community where I will get a chance to learn, explore, co-create, with fellow contributors.
