### ISSUE TITLE
是不是还没有支持多语言

### ISSUE THREAD

**Issue by Leobuaa** [mylxsw/aidea#13]
感觉可能需要支持多语言。
需要的话，我可以帮忙支持～

**Comment by mylxsw** [comment]
感谢🙏，多语言是有做的，不过不太完整，有些翻译拿不准，只有部分内容多语言（目前只有英文），还有一些没有完全兼容，代码在这里哈，欢迎贡献！

https://github.com/mylxsw/aidea/blob/main/lib/lang/lang.dart
