### ISSUE TITLE
关于注册方法

### ISSUE THREAD

**Issue by Phantom-HY** [mylxsw/aidea#14]
注册方法能不能增加一个邮箱注册

**Comment by mylxsw** [comment]
没问题，最开始做的就是邮箱注册，后面为了减少用户注册成本，就注释掉了，既然开源了，后面会重新开放出来

**Comment by Phantom-HY** [comment]
没想到你回复这么快，感谢你看了我的意见😀

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年9月2日 23:18
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mylxsw/aidea] 关于注册方法 (Issue #14)


没问题，最开始做的就是邮箱注册，后面为了减少用户注册成本，就注释掉了，既然开源了，后面会重新开放出来

**Comment by mylxsw** [comment]
1.0.5 版本支持
