### ISSUE TITLE
m1 mac book pro 显示无法打开app

### ISSUE THREAD

**Issue by yhx123** [mylxsw/aidea#2]
![image](https://github.com/mylxsw/aidea/assets/15153075/426d70bd-fd1b-4078-9eb9-5588a917b023)

**Comment by mylxsw** [comment]
应该是因为没有上架 App Store，所以 Apple  不让安装，可以尝试以下方案来解决

1. 先尝试 [Mac软件无法打开“apple无法检查其是否包含恶意软件”如何解决？](https://baijiahao.baidu.com/s?id=1725986970031092038&wfr=spider&for=pc) ， 在隐私和安全性中手动允许打开 AIdea
2. 如果还是提示无法打开，再尝试 [macOS无法验证此App，包含恶意软件或已损坏，无法打开](https://zhuanlan.zhihu.com/p/385082722)，允许从任意来源安装应用就可以运行了。

**Comment by uyoungco** [comment]
macbook pro 2019 无法打开

**Comment by Nasamars** [comment]
MacBook Air M1 也打不开 源码下回来也编译不成

**Comment by mylxsw** [comment]
大家试试按照“允许从任意来源安装”后能不能打开哈，参考这个 https://zhuanlan.zhihu.com/p/385082722

<img width="827" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/11f25d55-d4ef-4a41-bcea-f8c693731541">

**Comment by Nasamars** [comment]
其实已经这么设置过了

**Comment by mylxsw** [comment]
> MacBook Air M1 也打不开 源码下回来也编译不成

本地编译失败应该和 Xcode 开发者证书的设置有关系，具体怎么搞我还得研究下，后面再更新到文档。

**Comment by yhx123** [comment]
> 

是的，我的一直都是开着，允许所有的，这个提示就不是安全性的问题呀

**Comment by yhx123** [comment]
> 应该是因为没有上架 App Store，所以 Apple 不让安装，可以尝试以下方案来解决
> 
> 1. 先尝试 [Mac软件无法打开“apple无法检查其是否包含恶意软件”如何解决？](https://baijiahao.baidu.com/s?id=1725986970031092038&wfr=spider&for=pc) ， 在隐私和安全性中手动允许打开 AIdea
> 2. 如果还是提示无法打开，再尝试 [macOS无法验证此App，包含恶意软件或已损坏，无法打开](https://zhuanlan.zhihu.com/p/385082722)，允许从任意来源安装应用就可以运行了。

你看看我的截图，和你给的链接里的报错不一样的，我的已经开了允许所有软件，还是不能打开

**Comment by mylxsw** [comment]
稍安勿躁，我找个虚拟机试试，我电脑可以打开，也是 M1 的，没想到会有这个问题

**Comment by mylxsw** [comment]
临时解决方案，命令行执行

```bash
sudo codesign -f -s - /Applications/AIdea.app
```

<img width="1125" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/5ef3fbe1-6cb3-4a64-9c17-82dd8c864ac7">

**Comment by lidada-qd** [comment]
![image](https://github.com/mylxsw/aidea/assets/66238476/b1837eed-4dae-4aa9-ac15-28818a944045)
使用代理地址不行吗

**Comment by mylxsw** [comment]
> 

 你这个是跨域问题，用的代理不支持跨域，所以 Web 端没法使用，找一个支持跨域的代理或者在响应头中添加跨域的响应头。

> 我用的 https://github.com/justjavac/openai-proxy 这个项目，使用 deno 部署的代理是可以直接使用的，有跨域的支持，仅供参考。

<img width="1590" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/96e243da-33fd-4a9b-8913-7035aef1a2f3">

**Comment by mylxsw** [comment]
Mac 桌面端应用无法打开， [ 临时解决方案](https://github.com/mylxsw/aidea#1-mac-%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BA%94%E7%94%A8%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E6%8A%A5%E9%94%99%E5%A6%82%E4%B8%8B)
