### ISSUE TITLE
编译web版失败

### ISSUE THREAD

**Issue by allentown521** [mylxsw/aidea#28]
已pull最新代码，编译android版正常，编译web版失败：
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/sqflite_common_ffi_web-0.3.6/lib/src/sqflite_ffi_impl_web.dart:19:7: Error: The non-abstract class 'SqfliteFfiHandlerWeb' is missing implementations for these members:
 - SqfliteFfiHandler.readDatabaseBytesPlatform
 - SqfliteFfiHandler.writeDatabaseBytesPlatform
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SqfliteFfiHandlerWeb extends SqfliteFfiHandler {
      ^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/sqflite_common_ffi-2.3.0+2/lib/src/sqflite_ffi_handler.dart:19:21: Context: 'SqfliteFfiHandler.readDatabaseBytesPlatform' is defined here.
  Future<Uint8List> readDatabaseBytesPlatform(String path);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/sqflite_common_ffi-2.3.0+2/lib/src/sqflite_ffi_handler.dart:16:16: Context: 'SqfliteFfiHandler.writeDatabaseBytesPlatform' is defined here.
  Future<void> writeDatabaseBytesPlatform(String path, Uint8List bytes);
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by mylxsw** [comment]
sqflite_common_ffi 依赖包升级后 sqflite_common_ffi_web 没有升级导致，最新的 develop 分支已经修复该问题，下个版本发布
