### ISSUE TITLE
help to create an account

### ISSUE THREAD

**Issue by Jack01-bob** [mylxsw/aidea#29]
how do I create a new account

**Comment by KhieuDuong** [comment]
We can not create account without china phone number

**Comment by mylxsw** [comment]
We are about to support the method of using email as an account login method.

**Comment by KhieuDuong** [comment]
Hi admin, can you support me create account by email “
***@***.***”

Best Regards!

2023년 9월 17일 (일) 오전 2:13, 管宜尧 ***@***.***>님이 작성:
