### ISSUE TITLE
Web 端聊天界面input影响输入法的第一个字符

### ISSUE THREAD

**Issue by joriewong** [mylxsw/aidea#3]
<img width="167" alt="image" src="https://github.com/mylxsw/aidea/assets/11408040/5379ebb2-2507-4670-b9cb-464a18a3a5c1">
<img width="817" alt="image" src="https://github.com/mylxsw/aidea/assets/11408040/9fe26ab5-3859-412d-82e0-22f0409287ed">

**Comment by joriewong** [comment]
browser: 
Microsoft Edge
版本 115.0.1901.203 (正式版本) (arm64)

**Comment by joriewong** [comment]
用搜狗测的，mac自带输入法也是同样问题

**Comment by mylxsw** [comment]
是有这么个 bug，我先研究下怎么解决

**Comment by gxr404** [comment]
> 是有这么个 bug，我先研究下怎么解决

试了一下 好像是由于`_textController.addListener`里面调用`setState`影响的
```dart
_textController.addListener(() {
    setState(() {});
});
```
不确定大佬`_textController.addListener`里面调用`setState`是否是必须的,请教下

**Comment by mylxsw** [comment]
> > 是有这么个 bug，我先研究下怎么解决
> 
> 试了一下 好像是由于`_textController.addListener`里面调用`setState`影响的
> 
> ```dart
> _textController.addListener(() {
>     setState(() {});
> });
> ```
> 
> 不确定大佬`_textController.addListener`里面调用`setState`是否是必须的,顺便请教下😂

 这个不能去掉，它控制了输入框右侧的按钮，有内容时是“发送”，没有内容时是“语音”。

**Comment by mylxsw** [comment]
找到原因了，是 TextField 有这么个 Bug，替换成 TextFormField  就可以了

**Comment by mylxsw** [comment]
已在 [1.0.4](https://github.com/mylxsw/aidea/releases/tag/1.0.4) 版本解决。
