### ISSUE TITLE
关于一些小问题

### ISSUE THREAD

**Issue by Jiemking** [mylxsw/aidea#30]
编辑框输入内容有字数限制
问AI写代码的时候 预览代码框没有 复制 (很麻烦) 我是windows系统的 然后就是那个 文本形式 鼠标选中的时候有时候可以有时候不行 不能滚动选中

其他功能都挺好的 没什么问题。

**Comment by mylxsw** [comment]
这里的复制体验确实不太好，后面想办法优化下

**Comment by LeeeSe** [comment]
字数限制（或者是行数限制？）是 AIdea 特有的吗？特意充值用 GPT4 review 代码，发现输入不了多少行，难受的一

**Comment by Jiemking** [comment]
> 字数限制（或者是行数限制？）是 AIdea 特有的吗？特意充值用 GPT4 review 代码，发现输入不了多少行，难受的一

应该是做了处理 我用别的gpt 暂时没有出现字数输入限制的 唯一就是gpt官方 上新闻的token会有限制

**Comment by mylxsw** [comment]
下个版本放开字数限制，只限制模型最大允许的上下文token数量

**Comment by Jiemking** [comment]
> 下个版本放开字数限制，只限制模型最大允许的上下文令牌数量

好的 辛苦了

**Comment by mylxsw** [comment]
最新的 1.0.6 版本，字数限制已经放开。
