### ISSUE TITLE
Mac OS 13.5.2 (22G91)无法使用

### ISSUE THREAD

**Issue by fandongtongxue** [mylxsw/aidea#33]
![WX20230918-092340](https://github.com/mylxsw/aidea/assets/21986591/cd53beb8-e807-482b-88f0-e5336ee2fe47)

**Comment by mylxsw** [comment]
因为没有上架 App Store，Mac 用户需要在安全设置中启用允许安装任意来源应用，终端输入

```bash
sudo spctl --master-disable
```

**Comment by fandongtongxue** [comment]
好的，我试试，谢谢

**Comment by mylxsw** [comment]
现在打开显示什么呢，还是软件已损坏吗
