### ISSUE TITLE
Web 端使用最新版的 Chrome 浏览器 117.0.5938.88 无法使用聊天、数字人

### ISSUE THREAD

**Issue by mylxsw** [mylxsw/aidea#36]
使用最新版的 Chrome 浏览器（版本 117.0.5938.88）访问，聊天和数字人报错

<img width="394" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/227c185f-2644-4d1c-918f-0bfde04eb387">

```bash
Expected a value of type 'Iterator', but got one of type 'DomIterator'
```

或者 

<img width="420" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/c8cedf64-5094-4056-b687-9bc06a3e5755">

```bash
NoSuchMethodError: method not found: 'MA' Receiver: Instance of 'Headers Iterator' Arguments: []
```

**Comment by xixingya** [comment]
移动端web也有类似问题，但是我打包web的方式改成makefile中的flutter build web --web-renderer canvaskit --release 这个后，就没问题了

**Comment by xixingya** [comment]
实测，118版本的chrome在这个打包方式下也没问题

**Comment by mylxsw** [comment]
最新版本[1.0.7](https://github.com/mylxsw/aidea/releases/tag/1.0.7)已修复该问题，使用 WebSocket 代替 SSE 协议

> 注意：服务端需要同时升级到最新版本。
