### ISSUE TITLE
 run on edge or chrome error,how to solve it?

### ISSUE THREAD

**Issue by luoyou** [mylxsw/aidea#47]
Waiting for connection from debug service on Chrome...
/C:/Users/luo/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/fetch_api-1.0.2/lib/src/iterator.dart:24:30: Error: `@staticInterop` classes cannot have external extension members with type parameters.
Try using a Dart extension member if you need type parameters instead.
  external IteratorResult<T> next();
                             ^
Failed to compile application.

**Comment by AndroidCrazyBoy** [comment]
+1

**Comment by Lee-Wang-Jing** [comment]
切换到develop分支运行就好了
