### ISSUE TITLE
1.0.6版本web端编译出错

### ISSUE THREAD

**Issue by wookkkkk** [mylxsw/aidea#52]
环境 win11 x64
Dart SDK version: 3.1.3 (stable)
Flutter 3.13.7 • channel stable
报错内容
Launching lib\main.dart on Edge in debug mode...
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/fetch_api-1.0.2/lib/src/iterator.dart:24:30: Error: `@staticInterop` classes cannot have external extension members with type parameters.
Try using a Dart extension member if you need type parameters instead.
  external IteratorResult<T> next();
                             ^

**Comment by mylxsw** [comment]
切换到 develop 分支就可以了
