### ISSUE TITLE
有群吗

### ISSUE THREAD

**Issue by lingxyun** [mylxsw/aidea#7]

**Comment by josonfan** [comment]
同问 组个群啊

**Comment by mylxsw** [comment]
群来了，扫码加入

<img src="https://github.com/mylxsw/aidea/assets/2330911/bff2b9a7-7c60-4471-be71-d3b6a825c8e6" width="600"/>

**Comment by dearliuliu0522** [comment]
@mylxsw up，群超过200人了，能拉一下嘛？wx：dearliuliu0522

**Comment by mylxsw** [comment]
> @mylxsw up，群超过200人了，能拉一下嘛？wx：dearliuliu0522

加微信 x-prometheus 哈，拉你进群

![img](https://user-images.githubusercontent.com/2330911/265201673-655601c1-9371-4460-9657-c58521260336.png)
