### ISSUE TITLE
Please reduce the length of the messages or completion.

### ISSUE THREAD

**Issue by mkai97** [mylxsw/aidea#77]
聊天请求失败，模型 gpt-3.5-turbo: error, status code: 400, message: This model's maximum context length is 4097 tokens. However, you requested 4444 tokens (444 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.

然而我只是发了几个“你好”,问了一个问题, 我其他项目的使用这个openAI key的时候就没有这个问题.
![6131702973162_ pic](https://github.com/mylxsw/aidea/assets/53329864/26595b6d-31a8-4daa-84ad-d4a17b89414f)
![6121702973161_ pic](https://github.com/mylxsw/aidea/assets/53329864/cbf6a926-1b0d-4efd-bafc-0182cec444b2)
我该怎做才能正常使用,或者默认上下文功能怎么关闭呢?

谢谢.

**Comment by mylxsw** [comment]
服务端 Bug 导致，更新服务端代码为最新再试试

**Comment by mkai97** [comment]
> 服务端 Bug 导致，更新服务端代码为最新再试试

非常棒,问题解决了
