### ISSUE TITLE
mac 软件无法打开

### ISSUE THREAD

**Issue by zxdeya** [mylxsw/aidea#8]
2019 款 mac pro 
系统Ventura 13.4
隐私安全已经允许运行当前软件，任然无法打开

**Comment by zxdeya** [comment]
安全性也设置成任何来源，任然无法打开

**Comment by mylxsw** [comment]
参考这个试试 https://github.com/mylxsw/aidea/issues/2#issuecomment-1700554136

**Comment by eicky** [comment]
+1

**Comment by mylxsw** [comment]
临时解决方案，命令行执行

```bash
sudo codesign -f -s - /Applications/AIdea.app
```

<img width="1125" alt="image" src="https://github.com/mylxsw/aidea/assets/2330911/5ef3fbe1-6cb3-4a64-9c17-82dd8c864ac7">

**Comment by mylxsw** [comment]
Mac 桌面端应用无法打开， [ 临时解决方案](https://github.com/mylxsw/aidea#1-mac-%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BA%94%E7%94%A8%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E6%8A%A5%E9%94%99%E5%A6%82%E4%B8%8B)
